#!/bin/bash
# 通义千问（Qwen）配置脚本

echo "======================================"
echo "通义千问（Qwen）配置指南"
echo "======================================"
echo ""
echo "1. 获取 API Key："
echo "   - 访问：https://dashscope.aliyun.com/"
echo "   - 注册/登录阿里云账号"
echo "   - 进入控制台，创建 API Key"
echo ""
echo "2. 设置环境变量："
echo ""
echo "   说明：虽然使用 'openai' 库，但通过 base_url 指向阿里云服务"
echo "         实际调用的是通义千问（Qwen），不是 OpenAI"
echo ""
echo "   方式1：临时设置（当前终端有效）"
echo "   export OPENAI_API_BASE_URL=https://dashscope.aliyun.com/compatible-mode/v1"
echo "   export OPENAI_API_KEY=你的_qwen_api_key"
echo ""
echo "   方式2：永久设置（添加到 ~/.bashrc 或 ~/.zshrc）"
echo "   echo 'export OPENAI_API_BASE_URL=https://dashscope.aliyun.com/compatible-mode/v1' >> ~/.zshrc"
echo "   echo 'export OPENAI_API_KEY=你的_qwen_api_key' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "   方式3：创建 .env 文件（推荐）"
echo "   cat > .env << EOF"
echo "   OPENAI_API_BASE_URL=https://dashscope.aliyun.com/compatible-mode/v1"
echo "   OPENAI_API_KEY=你的_qwen_api_key"
echo "   EOF"
echo ""
echo "3. 测试连接："
echo "   python -c \"from openai import OpenAI; import os; client = OpenAI(base_url=os.getenv('OPENAI_API_BASE_URL'), api_key=os.getenv('OPENAI_API_KEY')); print(client.chat.completions.create(model='qwen-plus', messages=[{'role':'user','content':'你好'}]).choices[0].message.content)\""
echo ""
echo "4. 启动 RAG 系统："
echo "   python rag_system.py --index test_index_1"
echo ""
echo "======================================"

